import { TronWeb } from 'tronweb';

// USDT (TRC-20) on Tron mainnet. Any transfer the watcher sees that isn't
// from THIS exact contract is ignored, however convincing its name/symbol
// look — otherwise a worthless look-alike token could trick us into
// crediting real money for nothing. Overridable so this whole pipeline can
// be rehearsed end-to-end against Tron's Shasta/Nile testnet (using a test
// TRC-20 token) before ever touching mainnet USDT — see server/README.md.
export const USDT_CONTRACT_ADDRESS =
  process.env.USDT_CONTRACT_ADDRESS_OVERRIDE?.trim() || 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t';

// Standard BIP44 path for Tron (coin type 195). `m/44'/195'/0'/0/{index}`
// — one address per user, index assigned once via next_crypto_deposit_index()
// and never reused.
function derivationPath(index: number): string {
  return `m/44'/195'/0'/0/${index}`;
}

let cachedMnemonic: string | null | undefined;

// The ONLY place the master seed is ever read. Never logged, never sent
// anywhere, never stored in the database — only this env var (set once in
// Render's dashboard, generated by the one-time setup script — see
// server/README.md "Crypto deposits"). Every user's private key is
// re-derivable on demand from this seed + their stored derivation_index;
// losing the database loses no money, losing this env var (without a
// backup of the mnemonic) means the deposit addresses it controls can
// never be swept.
function getMasterMnemonic(): string | null {
  if (cachedMnemonic !== undefined) return cachedMnemonic;
  const mnemonic = process.env.TRON_MASTER_SEED?.trim();
  cachedMnemonic = mnemonic && mnemonic.length > 0 ? mnemonic : null;
  return cachedMnemonic;
}

export function cryptoDepositsEnabled(): boolean {
  return getMasterMnemonic() !== null;
}

export interface DerivedTronAccount {
  address: string;
  privateKey: string;
}

// Pure, deterministic, offline — no network call, so this is safe to call
// as often as needed (e.g. every time we need to re-derive a key to sweep
// an address) without hitting any rate limit.
export function deriveTronAccount(index: number): DerivedTronAccount {
  const mnemonic = getMasterMnemonic();
  if (!mnemonic) {
    throw new Error('TRON_MASTER_SEED is not set — crypto deposits are disabled');
  }
  const account = TronWeb.fromMnemonic(mnemonic, derivationPath(index));
  // TronWeb returns this 0x-prefixed; normalized to raw hex here since
  // that's what TronWeb's own signing APIs (used later for sweeping) expect,
  // and it avoids every caller needing to remember to strip it themselves.
  const privateKey = account.privateKey.startsWith('0x') ? account.privateKey.slice(2) : account.privateKey;
  return { address: account.address, privateKey };
}
